# Generated by Django 3.0.7 on 2020-06-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20200608_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telf',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
