# Generated by Django 3.0.7 on 2020-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20200608_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='entregado',
            field=models.BooleanField(verbose_name='Entregado?'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nro_pedido',
            field=models.IntegerField(verbose_name='Nro. de Pedido'),
        ),
    ]
